config/routes.rb
Rails.application.routes.draw do
  get 'publishers/new'
  get 'publishers/create'
  get 'publishers/update'
  get 'publishers/edit'
  get 'publishers/destroy'
  get 'publishers/show'
  get 'publishers/index'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/edit'
  get 'authors/destroy'
  get 'authors/show'
  get 'authors/index'
  get 'categories/new'
  get 'categories/create'
  get 'categories/update'
  get 'categories/edit'
  get 'categories/destroy'
  get 'categories/show'
  get 'categories/index'
  get 'books/new'
  get 'books/create'
  get 'books/update'
  get 'books/edit'
  get 'books/destroy'
  get 'books/index'
  get 'books/show'
  get 'about/index'

  get 'about' => 'about#index'
  root 'books#index'
  resources :books
  resources :authors
  resources :categories
  resources :publishers

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
    validates :first_name, presence:true
    validates :last_name, presence:true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :category
    belongs_to :author
    belongs_to :publisher
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
    validates :name, presence:true,length:{minimum:3}
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :books
    validates :name, presence:true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = 'About Us'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  
  def new
    @page_title = 'Add a new book'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:notice] = 'author created!'
      redirect_to authors_path
    else
      render 'new'
    end    
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def show
  end

  def index
  end

  private
  def author_params
   params.require(:author).permit(:first_name, :last_name)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @page_title = 'Add a new book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to books_path
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    @books = Book.all
   
  end

  def show
    @book = Book.find(params[:id])
  end

  private
  def book_params
   params.require(:book).permit(:title ,:category_id, :author_id, :publisher_id, :isbn, :price, :buy, :format, :except ,:pages, :year ,:coverpath)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def new
    @page_title = 'Add a new category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'category created!'
      redirect_to categories_path
    else
      render 'new'
    end    
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def show
  end

  def index
  end

  private
  def category_params
   params.require(:category).permit(:name)
  end

end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  
  def new
    @page_title = 'Add a new publisher'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = 'publisher created!'
      redirect_to publishers_path
    else
      render 'new'
    end    
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def show
  end

  def index
  end

  private
  def publisher_params
   params.require(:publisher).permit(:name)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
<h1><%= @page_title %></h1>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/authors/new.html.erb
<h2>Add new Author</h2>
<%= form_for  @author  do |f| %>

<% if @author.errors.any? %>
    <% @author.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger">
            <%= msg %>
        </div>   
    <% end %>
<% end %>

<div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name,class:'form-control' %><br/>
</div>

<div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name,class:'form-control' %><br/>
</div>

<div class="form-group">
    <%= f.submit "Submit",class:'btn btn-primary' %>
    <%= link_to 'Cancel' ,books_path, class: 'btn btn-default' %>
</div>
<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div id="books-index">
   <% @books.each_slice(4)  do |book| %>
        <div class="row">
            <% book.each do |book| %>
               <div class="col-md-3">
                 <h4><%= book.title %></h4>
                <%= image_tag(book.coverpath) %>
                <%= link_to 'Read More', book_path(book),class: 'btn btn-primary'%>
               </div>
            <% end %>
        </div>
   <% end %>
</div>

app/views/books/new.html.erb
<h2>Add new Book</h2>
<%= form_for  @book  do |f| %>
<div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title,class:'form-control' %><br/>
</div>

<div class="form-group">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn,class:'form-control' %><br/>
</div>


<div class="form-group">
    <%= f.label :year %><br>
    <%= f.text_field :year,class:'form-control' %><br/>
</div>

<div class="form-group">
    <%= f.label :coverpath %><br>
    <%= f.text_field :coverpath,class:'form-control' %><br/>
</div>



<div class="form-group">
    <%= f.label :category %><br>
    <%= f.select :category_id, Category.all.collect {|x| [x.name ,x.id]}, {:include_blank => 'Select One'},class:'form-control' %><br><br>
</div>

<div class="form-group">
    <%= f.label :author %><br>
    <%= f.select :author_id, Author.all.collect {|x| [x.first_name+ ' '+x.last_name,x.id]}, {:include_blank => 'Select One'},class:'form-control' %><br><br>
</div>

<div class="form-group">
    <%= f.label :publisher %><br>
    <%= f.select :publisher_id, Publisher.all.collect {|x| [x.name ,x.id]}, {:include_blank => 'Select One'},class:'form-control' %><br><br>
</div>

<div class="form-group">
    <%= f.label :format %><br>
    <%= f.text_field :format,class:'form-control' %><br/>
</div>

<div class="form-group">
    <%= f.label :except %><br>
    <%= f.text_area :except,class:'form-control' %><br/>
</div>


<div class="form-group">
    <%= f.label :pages %><br>
    <%= f.number_field :pages,class:'form-control' %><br/>
</div>


<div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price,class:'form-control' %><br/>
</div>


<div class="form-group">
    <%= f.label :buy %><br>
    <%= f.text_field :buy,class:'form-control' %><br/>
</div>

<div class="form-group">
    <%= f.submit "Submit",class:'btn btn-primary' %>
    <%= link_to 'Cancel' ,books_path, class: 'btn btn-default' %>
</div>


<% end %>

app/views/books/show.html.erb
<div id="books-show">
    <h2><%= @book.title %></h2>
    <div class="books-show-left">
        <%= image_tag(@book.coverpath) %>
    </div>
    <div class="books-show-right">
        <h3>Book Info</h3>
        <ul>
            <li><strong>Category:</strong><%= @book.category.name %></li>
            <li><strong>Author:</strong><%= @book.author.first_name %></li>
            <li><strong>Publisher:</strong><%= @book.publisher.name %></li>
            <li><strong>Year:</strong><%= @book.year %></li>
            <li><strong>ISBN:</strong><%= @book.isbn %></li>
            <li><strong>Format:</strong><%= @book.format %></li>
            <li><strong>Pages:</strong><%= @book.pages %></li>
        </ul>
        <%= link_to "Buy for "+ @book.price, @book.buy ,class:'btn btn-success', target:"_blank"%>
    </div>
    
    <div class="clearfix"></div>
    <h4>Except</h4>
    <p><%= @book.except %></p>

</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h2>Add a new Category</h2>
<%= form_for  @category  do |f| %>
<% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger">
            <%= msg %>
        </div>   
    <% end %>
<% end %>
<div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name,class:'form-control' %><br/>
</div>
<div class="form-group">
    <%= f.submit "Submit",class:'btn btn-primary' %>
    <%= link_to 'Cancel' ,books_path, class: 'btn btn-default' %>
</div>
<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title ?  @page_title : 'welcome' %> | The Bookstore</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <nav class="navbar navbar-expand-lg navbar-light bg-light">
 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="<%= params[:controller] == 'books' ? 'active' : ''  %>">
        <%= link_to 'Home', root_path, class: "nav-link" %>       
      </li>

      <li class="<%= params[:controller] == 'about' ? 'active' : ''  %>"">
        <%= link_to 'About', about_path, class: "nav-link" %>       
      </li> 
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Add Item
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <ul>
            <li><%= link_to 'Book', new_book_path, class: "nav-link" %></li>
            <li><%= link_to 'Category', new_category_path, class: "nav-link" %></li>
            <li><%= link_to 'Author', new_author_path, class: "nav-link" %></li>
            <li><%= link_to 'Publishers', new_publisher_path, class: "nav-link" %></li>
          </ul>
        </div>
      </li>
     
    </ul>
   
  </div>
</nav>
<header>
  <div class="container">
    <h1>The Bookstore <small><%= @page_title ?  @page_title : 'welcome' %></small></h1>
  </div>
</header>

   <section>
    <div class="container">
       <div class="row">
        <div class="col-md-8">
        
          <% if flash[:notice] %>
            <div class="alert alert-success"><%= flash[:notice] %></div>
          <% end %>

           <% if flash[:alert] %>
            <div class="alert alert-danger"><%= flash[:alert] %></div>
          <% end %>

          <%= yield %>
        </div>
        <div class="col-md-4">
           <%= render 'partials/sidebar' %>
        </div>
       </div>
    </div>
   </section>

   <footer>
    <div class="container">
      <p>Copyright &copy: 2014, All rights reserved </p>
    </div>
   </footer>
  </body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
<div class="card bg-light">
    <h3>location info</h3>
    <ul>
      <li>Atanu Marick</li>
      <li>Risra</li>
      <li>Trainee Associate Engg</li>
      <li>Web development</li>
    </ul>
</div>
<% end %>
<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
<ul class="list-group">  
  <li class="list-group-item">Ruby On Rails</li>
  <li class="list-group-item">PHP</li>
  <li class="list-group-item">HTML5</li>
</ul>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h1>Publishers#edit</h1>
<p>Find me in app/views/publishers/edit.html.erb</p>

app/views/publishers/index.html.erb
<h1>Publishers#index</h1>
<p>Find me in app/views/publishers/index.html.erb</p>

app/views/publishers/new.html.erb
<h2>Add new publisher</h2>

<%= form_for  @publisher  do |f| %>
<% if @publisher.errors.any? %>
    <% @publisher.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger">
            <%= msg %>
        </div>   
    <% end %>
<% end %>

<div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name,class:'form-control' %><br/>
</div>

<div class="form-group">
    <%= f.submit "Submit",class:'btn btn-primary' %>
    <%= link_to 'Cancel' ,books_path, class: 'btn btn-default' %>
</div>
<% end %>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>